### PR TITLE
Add support for quick fixes

### LINKED ISSUE #458: Add support for quick fixes
### What is the problem you're trying to solve?

Add support for quick fixes using the computeEditInfo option.
I think this will make it easier to see how computeEditInfo works.

### What solution would you like to see?

Add support for quick fixes using the computeEditInfo option.

It seems that the documentation for computeEditInfo is not published yet. 
Should we wait for the documentation to be published first?
Related to https://github.com/stylelint/stylelint/issues/8341

### PR DESCRIPTION
**Pull request by ota-meshi**
> Which issue, if any, is this issue related to?

Closes #458

> Is there anything in the PR that needs further explanation?

This PR adds support for quick fixes.

I think you can try the following code:

CODE: 

```css
a { color: rgb(0 0 0 / 0.5) }
```

The `computeEditInfo` option is not released, so please use the current main branch package released in `pkg.pr.new`:

Dependencies:

```json
{
  "stylelint": "https://pkg.pr.new/stylelint@eec62e5",
  "stylelint-config-standard": "latest"
}
```

### CODE REVIEW

**Review by ybiquitous — APPROVED** [review]
Thank you, this is great! 🎉 

Here's my demo on [this PR's preview site](https://deploy-preview-459--chimerical-trifle-8d3c21.netlify.app/#N4Igxg9gJgpiBcICGACYLIBsICd4pwHMAjACgAYVLKB6FAVnIFIBKFAXxABoQAzAS0wwAckgC2cRDAAe4gA5CAdGADOK7uAgA7AYQQhgAHS0oUhkDIAuMLVBXn8AbWOnT5lZYCeQzPy2WAWkgdfkIAjyRbJBwocxcUAF1jTh5g3QAxXDEkS30AKxVtDVg5dUQjEzMQD28YX38HKoALS0tS+BoaOQBrQkU5HEUtGAB3GhqfP0sAARgYMAA2ACYYenMuePcvSf8g7V1wy0ioaNiEKswcmA84rU52IA):

https://github.com/user-attachments/assets/4b593b2a-0a73-4bed-85a8-6d3e2adc4ecd

**Review by jeddy3 — APPROVED** [review]
This is amazing, thank you! ❤️ 

> I think this will make it easier to see how `computeEditInfo` works.

I totally agree. It's a fantastic demostration of `computeEditInfo` in action.

(It's great to see your `pkg.pr` stuff in action, too. It'll be particularly useful as we rollout `computeEditInfo` to other rules in PRs.)

File: src/demo.ts [hunk 1]
```diff
@@ -310,4 +372,42 @@ export async function mount({ element, init, listeners }: MountOptions) {
...
+	 * Create quick-fix code action.
+	 */
+	function createQuickFixCodeAction(
+		title: string,
+		marker: editor.IMarkerData,
+		model: editor.ITextModel,
+		fix: stylelint.EditInfo,
+	): languages.CodeAction {
+		const start = model.getPositionAt(fix.range[0]);
+		const end = model.getPositionAt(fix.range[1]);
```
Comment (romainmenke) [inline src/demo.ts:386]: Awesome to see how this integrates.
Makes me feel confident that we are on the right track.

Thank you so much for working on this @ota-meshi 🙇
